server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/PAMiW
          jwk-set-uri: http://keycloak:8080/realms/PAMiW/protocol/openid-connect/certs
    basic:
      enabled: false
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
      validator:
        apply_to_ddl: true
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


app:
  jwt:
    issuer-uri: http://keycloak:8080/realms/PAMiW
    resource-client-ids: noted